Add codeowners parsing
elhub/gh-dxp pull request #41
Opened 2024-06-19 20:56 UTC by michaeloa

Summary:
- Handle no file input
- Remove old CODEOWNERS
- Add CODEOWNERS parsing functionality to gh
- Add owners functionality to gh
- Test local GO params
- Update TC settings

Issue ID(s): TDX-522

Testing:
- [ ] Unit Tests
- [ ] Integration Tests
- Test Command: make check

Documentation:
- No updates

2024-06-20 08:50 UTC, johannes-gs requested changes
I think this commit does more than what is advertised in the title. Would appreciate it if you could split it into two

2024-06-20 08:50 UTC, jan-resaland-statnett approved these changes

2024-06-20 09:00 UTC, michaeloa commented
> I think this commit does more than what is advertised in the title. Would appreciate it if you could split it into two

Should probably have done that to begin with, but didn't realize that I'd need to update the template files until later. Updated the description to clarify what the change does.

2024-06-24 10:02 UTC, johannes-gs approved these changes

2024-06-24 10:13 UTC, merged